name: Daily Go Script Execution

on:
  schedule:
    - cron: "0 3 * * *" 
  workflow_dispatch: 

jobs:
  run-go-script:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23" 

      - name: Export Environment Variables
        run: |
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> $GITHUB_ENV

      - name: Run Go Script
        run: go run main.go
