name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    name: Build & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install Dependencies
        run: go mod tidy

      - name: Build Project
        run: go build -v ./...

      - name: Install Linter
        run: go install golang.org/x/lint/golint@latest

      - name: Run Linter
        run: golint ./... || true
